spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/manager
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.itest.web.dao

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30